run_config:
  author: smf2659
  name: iris-decision-tree
  version: tiny

train_test_split:
  random_state: 343
  test_size: 0.2

model:
  type: DecisionTreeClassifier # Must be one of the compatible models from pipeline
  params: # Should map to keyword arguments accepted by the above model type
    random_state: 343
    max_features: 3
    max_depth: 5
